//
//  CountryCode.swift
//  MultiBusiness-Vendor
//
//  Created by ilhan serhan ipek on 9.04.2024.
//

import Foundation

struct CountryCode: Identifiable {
    var id = UUID()
    var image: String
    var countryCode: String
    var countryName: String
}

extension CountryCode {
    static let countryCodes: [CountryCode] = [
        CountryCode(image: "afghanistan_flag", countryCode: "93", countryName: "Afghanistan"),
        CountryCode(image: "albania_flag", countryCode: "355", countryName: "Albania"),
        CountryCode(image: "algeria_flag", countryCode: "213", countryName: "Algeria"),
        CountryCode(image: "andorra_flag", countryCode: "376", countryName: "Andorra"),
        CountryCode(image: "angola_flag", countryCode: "244", countryName: "Angola"),
        CountryCode(image: "antartica_flag", countryCode: "672", countryName: "Antarctica"),
        CountryCode(image: "antigua_flag", countryCode: "1-268", countryName: "Antigua and Barbuda"),
        CountryCode(image: "argentina_flag", countryCode: "54", countryName: "Argentina"),
        CountryCode(image: "armenia_flag", countryCode: "374", countryName: "Armenia"),
        CountryCode(image: "australia_flag", countryCode: "61", countryName: "Australia"),
        CountryCode(image: "austria_flag", countryCode: "43", countryName: "Austria"),
        CountryCode(image: "azerbaijan_flag", countryCode: "994", countryName: "Azerbaijan"),
        CountryCode(image: "bahamas_flag", countryCode: "1-242", countryName: "Bahamas"),
        CountryCode(image: "bahrain_flag", countryCode: "973", countryName: "Bahrain"),
        CountryCode(image: "bangladesh_flag", countryCode: "880", countryName: "Bangladesh"),
        CountryCode(image: "barbados_flag", countryCode: "1-246", countryName: "Barbados"),
        CountryCode(image: "belarus_flag", countryCode: "375", countryName: "Belarus"),
        CountryCode(image: "belgium_flag", countryCode: "32", countryName: "Belgium"),
        CountryCode(image: "belize_flag", countryCode: "501", countryName: "Belize"),
        CountryCode(image: "benin_flag", countryCode: "229", countryName: "Benin"),
        CountryCode(image: "bhutan_flag", countryCode: "975", countryName: "Bhutan"),
        CountryCode(image: "bolivia_flag", countryCode: "591", countryName: "Bolivia"),
        CountryCode(image: "bosnia_flag", countryCode: "387", countryName: "Bosnia"),
        CountryCode(image: "botswana_flag", countryCode: "267", countryName: "Botswana"),
        CountryCode(image: "brazil_flag", countryCode: "55", countryName: "Brazil"),
        CountryCode(image: "brunei_flag", countryCode: "673", countryName: "Brunei"),
        CountryCode(image: "bulgaria_flag", countryCode: "359", countryName: "Bulgaria"),
        CountryCode(image: "burkina_flag", countryCode: "226", countryName: "Burkina Faso"),
        CountryCode(image: "burundi_flag", countryCode: "257", countryName: "Burundi"),
        CountryCode(image: "cambodia_flag", countryCode: "855", countryName: "Cambodia"),
        CountryCode(image: "cameroon_flag", countryCode: "237", countryName: "Cameroon"),
        CountryCode(image: "canada_flag", countryCode: "1", countryName: "Canada"),
        CountryCode(image: "cape_verde_flag", countryCode: "238", countryName: "Cape Verde"),
        CountryCode(image: "central_african_republic_flag", countryCode: "236", countryName: "Central African Republic"),
        CountryCode(image: "chad_flag", countryCode: "235", countryName: "Chad"),
        CountryCode(image: "chile_flag", countryCode: "56", countryName: "Chile"),
        CountryCode(image: "china_flag", countryCode: "86", countryName: "China"),
        CountryCode(image: "cocos_islands_flag", countryCode: "61", countryName: "Cocos Islands"),
        CountryCode(image: "colombia_flag", countryCode: "57", countryName: "Colombia"),
        CountryCode(image: "comoros_flag", countryCode: "269", countryName: "Comoros"),
        CountryCode(image: "costa_rica_flag", countryCode: "506", countryName: "Costa Rica"),
        CountryCode(image: "croatia_flag", countryCode: "385", countryName: "Croatia"),
        CountryCode(image: "cuba_flag", countryCode: "53", countryName: "Cuba"),
        CountryCode(image: "cyprus_flag", countryCode: "357", countryName: "Cyprus"),
        CountryCode(image: "czech_republic_flag", countryCode: "420", countryName: "Czech Republic"),
        CountryCode(image: "democratic_republic_of_the_congo_flag", countryCode: "243", countryName: "Democratic Republic of the Congo"),
        CountryCode(image: "denmark_flag", countryCode: "45", countryName: "Denmark"),
        CountryCode(image: "djibouti_flag", countryCode: "253", countryName: "Djibouti"),
        CountryCode(image: "dominica_flag", countryCode: "1-767", countryName: "Dominica"),
        CountryCode(image: "dominician_republic_flag", countryCode: "1-809", countryName: "Dominican Republic"),
        CountryCode(image: "east_timor_flag", countryCode: "670", countryName: "East Timor"),
        CountryCode(image: "ecuador_flag", countryCode: "593", countryName: "Ecuador"),
        CountryCode(image: "egypt_flag", countryCode: "20", countryName: "Egypt"),
        CountryCode(image: "el_salvador_flag", countryCode: "503", countryName: "El Salvador"),
        CountryCode(image: "england_flag", countryCode: "44", countryName: "England"),
        CountryCode(image: "equatorial_flag", countryCode: "240", countryName: "Equatorial Guinea"),
        CountryCode(image: "eritrea_flag", countryCode: "291", countryName: "Eritrea"),
        CountryCode(image: "estonia_flag", countryCode: "372", countryName: "Estonia"),
        CountryCode(image: "ethiopia_flag", countryCode: "251", countryName: "Ethiopia"),
        CountryCode(image: "fiji_flag", countryCode: "679", countryName: "Fiji"),
        CountryCode(image: "finland_flag", countryCode: "358", countryName: "Finland"),
        CountryCode(image: "france_flag", countryCode: "33", countryName: "France"),
        CountryCode(image: "gabon_flag", countryCode: "241", countryName: "Gabon"),
        CountryCode(image: "gambia_flag", countryCode: "220", countryName: "Gambia"),
        CountryCode(image: "georgia_flag", countryCode: "995", countryName: "Georgia"),
        CountryCode(image: "germany_flag", countryCode: "49", countryName: "Germany"),
        CountryCode(image: "ghana_flag", countryCode: "233", countryName: "Ghana"),
        CountryCode(image: "greece_flag", countryCode: "30", countryName: "Greece"),
        CountryCode(image: "greneda_flag", countryCode: "1-473", countryName: "Grenada"),
        CountryCode(image: "guatemala_flag", countryCode: "502", countryName: "Guatemala"),
        CountryCode(image: "guinea_flag", countryCode: "224", countryName: "Guinea"),
        CountryCode(image: "guyana_flag", countryCode: "592", countryName: "Guyana"),
        CountryCode(image: "haiti_flag", countryCode: "509", countryName: "Haiti"),
        CountryCode(image: "honduras_flag", countryCode: "504", countryName: "Honduras"),
        CountryCode(image: "hong_kong_flag", countryCode: "852", countryName: "Hong Kong"),
        CountryCode(image: "hungary_flag", countryCode: "36", countryName: "Hungary"),
        CountryCode(image: "iceland_flag", countryCode: "354", countryName: "Iceland"),
        CountryCode(image: "india_flag", countryCode: "91", countryName: "India"),
        CountryCode(image: "indonesia_flag", countryCode: "62", countryName: "Indonesia"),
        CountryCode(image: "iran_flag", countryCode: "98", countryName: "Iran"),
        CountryCode(image: "iraq_flag", countryCode: "964", countryName: "Iraq"),
        CountryCode(image: "ireland_flag", countryCode: "353", countryName: "Ireland"),
        CountryCode(image: "israel_flag", countryCode: "972", countryName: "Israel"),
        CountryCode(image: "italy_flag", countryCode: "39", countryName: "Italy"),
        CountryCode(image: "jamaica_flag", countryCode: "1-876", countryName: "Jamaica"),
        CountryCode(image: "japan_flag", countryCode: "81", countryName: "Japan"),
        CountryCode(image: "jordan_flag", countryCode: "962", countryName: "Jordan"),
        CountryCode(image: "kazakhstan_flag", countryCode: "7", countryName: "Kazakhstan"),
        CountryCode(image: "kenya_flag", countryCode: "254", countryName: "Kenya"),
        CountryCode(image: "kiribati_flag", countryCode: "686", countryName: "Kiribati"),
        CountryCode(image: "kosovo_flag", countryCode: "383", countryName: "Kosovo"),
        CountryCode(image: "kuwait_flag", countryCode: "965", countryName: "Kuwait"),
        CountryCode(image: "kyrgyzstan_flag", countryCode: "996", countryName: "Kyrgyzstan"),
        CountryCode(image: "laos_flag", countryCode: "856", countryName: "Laos"),
        CountryCode(image: "latvia_flag", countryCode: "371", countryName: "Latvia"),
        CountryCode(image: "lebanon_flag", countryCode: "961", countryName: "Lebanon"),
        CountryCode(image: "lesotho_flag", countryCode: "266", countryName: "Lesotho"),
        CountryCode(image: "liberia_flag", countryCode: "231", countryName: "Liberia"),
        CountryCode(image: "libya_flag", countryCode: "218", countryName: "Libya"),
        CountryCode(image: "liechtenstein_flag", countryCode: "423", countryName: "Liechtenstein"),
        CountryCode(image: "lithuania_flag", countryCode: "370", countryName: "Lithuania"),
        CountryCode(image: "luxembourg_flag", countryCode: "352", countryName: "Luxembourg"),
        CountryCode(image: "madagascar_flag", countryCode: "261", countryName: "Madagascar"),
        CountryCode(image: "malawi_flag", countryCode: "265", countryName: "Malawi"),
        CountryCode(image: "malaysia_flag", countryCode: "60", countryName: "Malaysia"),
        CountryCode(image: "maldives_flag", countryCode: "960", countryName: "Maldives"),
        CountryCode(image: "mali_flag", countryCode: "223", countryName: "Mali"),
        CountryCode(image: "malta_flag", countryCode: "356", countryName: "Malta"),
        CountryCode(image: "marshall_islands_flag", countryCode: "692", countryName: "Marshall Islands"),
        CountryCode(image: "mauritania_flag", countryCode: "222", countryName: "Mauritania"),
        CountryCode(image: "mauritius_flag", countryCode: "230", countryName: "Mauritius"),
        CountryCode(image: "mexico_flag", countryCode: "52", countryName: "Mexico"),
        CountryCode(image: "moldova_flag", countryCode: "373", countryName: "Moldova"),
        CountryCode(image: "monaco_flag", countryCode: "377", countryName: "Monaco"),
        CountryCode(image: "mongolia_flag", countryCode: "976", countryName: "Mongolia"),
        CountryCode(image: "montenegro_flag", countryCode: "382", countryName: "Montenegro"),
        CountryCode(image: "morocco_flag", countryCode: "212", countryName: "Morocco"),
        CountryCode(image: "mozambique_flag", countryCode: "258", countryName: "Mozambique"),
        CountryCode(image: "myanmar_flag", countryCode: "95", countryName: "Myanmar"),
        CountryCode(image: "namibia_flag", countryCode: "264", countryName: "Namibia"),
        CountryCode(image: "nauru_flag", countryCode: "674", countryName: "Nauru"),
        CountryCode(image: "nepal_flag", countryCode: "977", countryName: "Nepal"),
        CountryCode(image: "netherlands_flag", countryCode: "31", countryName: "Netherlands"),
        CountryCode(image: "netherlands_antilles_flag", countryCode: "599", countryName: "Netherlands Antilles"),
        CountryCode(image: "new_caledonia_flag", countryCode: "687", countryName: "New Caledonia"),
        CountryCode(image: "new_zealand_flag", countryCode: "64", countryName: "New Zealand"),
        CountryCode(image: "nicaragua_flag", countryCode: "505", countryName: "Nicaragua"),
        CountryCode(image: "niger_flag", countryCode: "227", countryName: "Niger"),
        CountryCode(image: "nigeria_flag", countryCode: "234", countryName: "Nigeria"),
        CountryCode(image: "niue_flag", countryCode: "683", countryName: "Niue"),
        CountryCode(image: "norfolk_island_flag", countryCode: "672", countryName: "Norfolk Island"),
        CountryCode(image: "north_korea_flag", countryCode: "850", countryName: "North Korea"),
        CountryCode(image: "northern_mariana_islands_flag", countryCode: "1-670", countryName: "Northern Mariana Islands"),
        CountryCode(image: "norway_flag", countryCode: "47", countryName: "Norway"),
        CountryCode(image: "oman_flag", countryCode: "968", countryName: "Oman"),
        CountryCode(image: "pakistan_flag", countryCode: "92", countryName: "Pakistan"),
        CountryCode(image: "palau_flag", countryCode: "680", countryName: "Palau"),
        CountryCode(image: "palestine_flag", countryCode: "970", countryName: "Palestine"),
        CountryCode(image: "panama_flag", countryCode: "507", countryName: "Panama"),
        CountryCode(image: "papua_new_guinea_flag", countryCode: "675", countryName: "Papua New Guinea"),
        CountryCode(image: "paraguay_flag", countryCode: "595", countryName: "Paraguay"),
        CountryCode(image: "peru_flag", countryCode: "51", countryName: "Peru"),
        CountryCode(image: "philippines_flag", countryCode: "63", countryName: "Philippines"),
        CountryCode(image: "poland_flag", countryCode: "48", countryName: "Poland"),
        CountryCode(image: "portugal_flag", countryCode: "351", countryName: "Portugal"),
        CountryCode(image: "qatar_flag", countryCode: "974", countryName: "Qatar"),
        CountryCode(image: "russia_flag", countryCode: "7", countryName: "Russia"),
        CountryCode(image: "rwanda_flag", countryCode: "250", countryName: "Rwanda"),
        CountryCode(image: "saint_kitts_and_nevis_flag", countryCode: "1-869", countryName: "Saint Kitts and Nevis"),
        CountryCode(image: "saint_lucia_flag", countryCode: "1-758", countryName: "Saint Lucia"),
        CountryCode(image: "saint_vincent_and_the_grenadines_flag", countryCode: "1-784", countryName: "Saint Vincent and the Grenadines"),
        CountryCode(image: "samoa_flag", countryCode: "685", countryName: "Samoa"),
        CountryCode(image: "san_marino_flag", countryCode: "378", countryName: "San Marino"),
        CountryCode(image: "sao_tome_and_principe_flag", countryCode: "239", countryName: "São Tomé and Príncipe"),
        CountryCode(image: "saudi_arabia_flag", countryCode: "966", countryName: "Saudi Arabia"),
        CountryCode(image: "senegal_flag", countryCode: "221", countryName: "Senegal"),
        CountryCode(image: "serbia_flag", countryCode: "381", countryName: "Serbia"),
        CountryCode(image: "seychelles_flag", countryCode: "248", countryName: "Seychelles"),
        CountryCode(image: "sierra_leone_flag", countryCode: "232", countryName: "Sierra Leone"),
        CountryCode(image: "singapore_flag", countryCode: "65", countryName: "Singapore"),
        CountryCode(image: "slovenia_flag", countryCode: "386", countryName: "Slovenia"),
        CountryCode(image: "solomon_islands_flag", countryCode: "677", countryName: "Solomon Islands"),
        CountryCode(image: "somalia_flag", countryCode: "252", countryName: "Somalia"),
        CountryCode(image: "south_africa_flag", countryCode: "27", countryName: "South Africa"),
        CountryCode(image: "south_korea_flag", countryCode: "82", countryName: "South Korea"),
        CountryCode(image: "south_sudan_flag", countryCode: "211", countryName: "South Sudan"),
        CountryCode(image: "spain_flag", countryCode: "34", countryName: "Spain"),
        CountryCode(image: "sri_lanka_flag", countryCode: "94", countryName: "Sri Lanka"),
        CountryCode(image: "sudan_flag", countryCode: "249", countryName: "Sudan"),
        CountryCode(image: "suriname_flag", countryCode: "597", countryName: "Suriname"),
        CountryCode(image: "svalbard_and_jan_mayen_flag", countryCode: "47", countryName: "Svalbard and Jan Mayen"),
        CountryCode(image: "swaziland_flag", countryCode: "268", countryName: "Swaziland"),
        CountryCode(image: "sweden_flag", countryCode: "46", countryName: "Sweden"),
        CountryCode(image: "switzerland_flag", countryCode: "41", countryName: "Switzerland"),
        CountryCode(image: "syria_flag", countryCode: "963", countryName: "Syria"),
        CountryCode(image: "taiwan_flag", countryCode: "886", countryName: "Taiwan"),
        CountryCode(image: "tanzania_flag", countryCode: "255", countryName: "Tanzania"),
        CountryCode(image: "thailand_flag", countryCode: "66", countryName: "Thailand"),
        CountryCode(image: "togo_flag", countryCode: "228", countryName: "Togo"),
        CountryCode(image: "tokelau_flag", countryCode: "690", countryName: "Tokelau"),
        CountryCode(image: "tonga_flag", countryCode: "676", countryName: "Tonga"),
        CountryCode(image: "turkey_flag", countryCode: "90", countryName: "Turkey"),
        CountryCode(image: "turkmenistan_flag", countryCode: "993", countryName: "Turkmenistan"),
        CountryCode(image: "tuvalu_flag", countryCode: "688", countryName: "Tuvalu"),
        CountryCode(image: "u.s._virgin_islands_flag", countryCode: "1-340", countryName: "U.S. Virgin Islands"),
        CountryCode(image: "uganda_flag", countryCode: "256", countryName: "Uganda"),
        CountryCode(image: "united_arab_emirates_flag", countryCode: "971", countryName: "United Arab Emirates"),
        CountryCode(image: "united_kingdom_flag", countryCode: "44", countryName: "United Kingdom"),
        CountryCode(image: "united_states_flag", countryCode: "1", countryName: "United States"),
        CountryCode(image: "uruguay_flag", countryCode: "598", countryName: "Uruguay"),
        CountryCode(image: "uzbekistan_flag", countryCode: "998", countryName: "Uzbekistan"),
        CountryCode(image: "vanuatu_flag", countryCode: "678", countryName: "Vanuatu"),
        CountryCode(image: "vatican_city_flag", countryCode: "379", countryName: "Vatican City"),
        CountryCode(image: "venezuela_flag", countryCode: "58", countryName: "Venezuela"),
        CountryCode(image: "vietnam_flag", countryCode: "84", countryName: "Vietnam"),
        CountryCode(image: "yemen_flag", countryCode: "967", countryName: "Yemen"),
        CountryCode(image: "zambia_flag", countryCode: "260", countryName: "Zambia"),
        CountryCode(image: "zimbabwe_flag", countryCode: "263", countryName: "Zimbabwe")
    ]
}
